### ISSUE TITLE
Error to send a message using website (reCaptcha)

### ISSUE THREAD

**Issue by bruno-esalq** [PhenoApps/phenoapps.org#1]
Page: https://www.phenoapps.org/contact/
Procedure:
- Tried to send a message
- Filled information (Full Name, Email Address, Message)
- Clicked Submit

Opens a webpage (https://formspree.io/f/xpzelojg) with an Error Message about Captcha
Error Message:
" Oops! reCAPTCHA failed.
Please complete reCAPTCHA before submit."
![error_phenoapps](https://github.com/user-attachments/assets/567f4ef2-bfae-4cf1-a8c5-ceb3e61bdb1a)

**Comment by trife** [comment]
@bruno-esalq looks like formspree changed their default captcha integration. should be updated and working now. thanks for letting me know!
